# -*- coding: utf-8 -*-
"""ai_learning_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-gfuAMUhA_Y6E0neBDZlrroLPgxdkFnq
"""

!pip install -q sentence-transformers pandas textblob datasets pydantic huggingface_hub gradio

import pandas as pd
import json
import re
import os
from datetime import datetime
from textblob import TextBlob
from huggingface_hub import InferenceClient
from typing import List, Dict, Optional
import gradio as gr

print("🚀 Initializing AI Skill Gap Detector v5.0...")

# Use environment variable
HF_TOKEN = os.getenv("HF_TOKEN", "")
client = InferenceClient("mistralai/Mistral-7B-Instruct-v0.3", token=HF_TOKEN)

print("✅ Mistral-7B Client initialized with structured output support")

def extract_json_robust(response_text: str) -> Optional[Dict]:
    """
    Multi-strategy JSON extraction from LLM output.
    Handles markdown code blocks, extra text, and nested structures.
    """
    # Strategy 1: Find JSON in markdown code blocks
    code_block_pattern = r'```(?:json)?\s*([\s\S]*?)```'
    matches = re.findall(code_block_pattern, response_text)
    if matches:
        for match in matches:
            try:
                return json.loads(match.strip())
            except json.JSONDecodeError:
                continue

    # Strategy 2: Find outermost JSON object braces
    try:
        start = response_text.find('{')
        end = response_text.rfind('}')
        if start != -1 and end != -1 and end > start:
            return json.loads(response_text[start:end+1])
    except json.JSONDecodeError:
        pass

    # Strategy 3: Line-by-line JSON detection (for multiline)
    lines = response_text.split('\n')
    json_buffer = []
    in_json = False
    brace_count = 0

    for line in lines:
        if '{' in line and not in_json:
            in_json = True
            json_buffer = []

        if in_json:
            json_buffer.append(line)
            brace_count += line.count('{') - line.count('}')

            if brace_count == 0 and '{' in ''.join(json_buffer):
                try:
                    return json.loads('\n'.join(json_buffer))
                except json.JSONDecodeError:
                    continue

    return None

def detect_skill_gaps_llm(description: str, notes: str) -> List[str]:
    """
    Context-specific skill gap detection with strict validation.
    NO hardcoded fallbacks - forces LLM to reason from context.
    """

    prompt = f"""<s>[INST] You are a precise technical skill analyzer. Your task is to identify SPECIFIC skill gaps based on the provided task and employee notes.

TASK DESCRIPTION:
{description[:400]}

EMPLOYEE NOTES (Struggles/Confusions):
{notes[:300]}

ANALYSIS INSTRUCTIONS:
1. Identify exactly 2-3 specific technical concepts the employee is missing
2. Each skill gap must be:
   - A concrete technical term (e.g., "JWT token validation", "SQL query execution plans")
   - Derived DIRECTLY from the task description and employee notes
   - Specific enough to search for in documentation
3. DO NOT use generic terms like "Programming", "Development", "Technical Skills"
4. If the task mentions Flask → identify specific Flask concepts (blueprints, SQLAlchemy integration)
5. If the task mentions SQL → identify specific SQL concepts (indexing strategies, execution plans)

OUTPUT FORMAT (STRICT JSON):
{{
  "skill_gaps": [
    "specific technical concept 1",
    "specific technical concept 2"
  ],
  "reasoning": "brief explanation of why these gaps were identified"
}}

Be precise and context-specific. [/INST]</s>"""

    try:
        response = client.text_generation(
            prompt,
            max_new_tokens=200,
            temperature=0.15,  # Slightly higher for diversity
            stop_sequences=["</s>"]
        )

        parsed = extract_json_robust(response)

        if parsed and "skill_gaps" in parsed:
            gaps = parsed["skill_gaps"]
            # Validate: must be specific (multi-word) and context-relevant
            validated_gaps = []
            for gap in gaps:
                gap = gap.strip()
                # Must be more than 2 words and not generic
                if (len(gap.split()) >= 2 and
                    gap.lower() not in ["technical skill gap", "programming", "development"] and
                    len(gap) > 10):
                    validated_gaps.append(gap)

            if validated_gaps:
                return validated_gaps[:3]

        # If parsing fails, return empty to trigger context-aware fallback
        return []

    except Exception as e:
        print(f"⚠️ Skill detection error: {e}")
        return []

def get_contextual_fallback(task_desc: str, notes: str) -> List[str]:
    """
    Intelligent fallback based on keyword extraction from task description.
    Only used if LLM fails completely.
    """
    task_lower = task_desc.lower()
    notes_lower = notes.lower()

    # Technology-specific fallbacks
    if 'flask' in task_lower or 'sqlalchemy' in task_lower:
        return ["Flask blueprint architecture", "SQLAlchemy ORM session management"]
    elif 'sql' in task_lower or 'database' in task_lower or 'query' in task_lower:
        return ["SQL execution plan analysis", "Database indexing strategies"]
    elif 'react' in task_lower or 'frontend' in task_lower:
        return ["React hooks dependency management", "Component state optimization"]
    elif 'kubernetes' in task_lower or 'docker' in task_lower or 'ci/cd' in task_lower:
        return ["Kubernetes deployment configurations", "GitHub Actions workflow syntax"]
    elif 'python' in task_lower and ('excel' in task_lower or 'pdf' in task_lower):
        return ["Pandas data manipulation patterns", "ReportLab PDF generation"]
    else:
        return ["Core task-specific implementation patterns", "Relevant framework architecture"]

def generate_tutorial(skill_gap: str, task_context: str) -> Dict:
    """
    Generates specific learning resources with strict quality checks.
    """

    prompt = f"""<s>[INST] Create a precise learning resource for the following skill gap.

SKILL GAP TO ADDRESS: {skill_gap}
TASK CONTEXT: {task_context[:200]}

REQUIREMENTS:
1. Explanation: 2-3 sentences explaining the concept and WHY it matters for this specific task
2. Code: A 3-6 line working code example that directly demonstrates the skill
3. Resource: Official documentation URL only (no tutorials, no Medium articles)

QUALITY RULES:
- Code must be syntactically correct and runnable
- Explanation must connect to the task context
- No generic advice like "practice more" or "read docs"
- Be specific to the technology mentioned

OUTPUT FORMAT (STRICT JSON):
{{
  "tutorial": "Specific explanation tied to the task...",
  "code_snippet": "specific_code_example()",
  "resource_link": "https://official-docs.com/specific-page"
}}

Generate now: [/INST]</s>"""

    try:
        response = client.text_generation(
            prompt,
            max_new_tokens=350,
            temperature=0.2,
            stop_sequences=["</s>"]
        )

        parsed = extract_json_robust(response)

        if parsed and all(k in parsed for k in ["tutorial", "code_snippet", "resource_link"]):
            # Quality checks
            tutorial = parsed["tutorial"]
            code = parsed["code_snippet"]

            # Reject generic tutorials
            banned_phrases = ["learn through", "hands-on practice", "refer to", "documentation", "practice more"]
            if any(phrase in tutorial.lower() for phrase in banned_phrases):
                raise ValueError("Generic tutorial detected")

            # Code must be substantial
            if len(code.strip().split('\n')) < 2:
                raise ValueError("Code too short")

            return parsed

    except Exception as e:
        print(f"⚠️ Tutorial generation fallback for {skill_gap}: {e}")

    # Context-aware intelligent fallback
    return get_intelligent_fallback(skill_gap)

def get_intelligent_fallback(skill_gap: str) -> Dict:
    """Technology-specific fallback resources"""
    skill_lower = skill_gap.lower()

    fallbacks = {
        "flask": {
            "tutorial": "Flask blueprints allow modular application organization by separating routes into distinct components. SQLAlchemy integrates via application factory pattern for clean database session management.",
            "code_snippet": "from flask import Blueprint\nuser_bp = Blueprint('user', __name__)\n\n@user_bp.route('/login')\ndef login():\n    return db.session.query(User).filter_by(email=email).first()",
            "resource_link": "https://flask.palletsprojects.com/en/2.3.x/blueprints/"
        },
        "sql": {
            "tutorial": "SQL execution plans reveal how the database processes queries, showing index usage and join methods. Analyzing these identifies bottlenecks in multi-table aggregations.",
            "code_snippet": "EXPLAIN ANALYZE SELECT u.name, COUNT(o.id)\nFROM users u\nLEFT JOIN orders o ON u.id = o.user_id\nWHERE u.created_at > '2023-01-01'\nGROUP BY u.id;",
            "resource_link": "https://www.postgresql.org/docs/current/sql-explain.html"
        },
        "react": {
            "tutorial": "React useEffect handles side effects like API calls and subscriptions. The dependency array determines when the effect re-runs, preventing infinite loops or stale closures.",
            "code_snippet": "useEffect(() => {\n  const fetchData = async () => {\n    const data = await api.get('/users');\n    setUsers(data);\n  };\n  fetchData();\n}, [userId]); // Re-run when userId changes",
            "resource_link": "https://react.dev/learn/synchronizing-with-effects"
        },
        "kubernetes": {
            "tutorial": "GitHub Actions workflows define CI/CD pipelines using YAML syntax. Kubernetes deployment requires proper manifest configuration for container orchestration and service exposure.",
            "code_snippet": "name: Deploy to K8s\non: [push]\njobs:\n  deploy:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v3\n      - run: kubectl apply -f k8s/",
            "resource_link": "https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions"
        }
    }

    # Match fallback to skill gap
    for tech, fallback in fallbacks.items():
        if tech in skill_lower:
            return fallback

    # Generic but useful fallback
    return {
        "tutorial": f"{skill_gap} requires understanding core implementation patterns and best practices for production environments.",
        "code_snippet": f"# Implementation of {skill_gap}\ndef implement_solution():\n    # Add specific logic here\n    return optimized_result",
        "resource_link": "https://developer.mozilla.org/en-US/docs/Web"
    }

def analyze_text_metadata(description: str, notes: str) -> tuple:
    """Enhanced emotion detection with confidence scoring"""
    combined_text = f"{notes} {description}"
    blob = TextBlob(combined_text)
    polarity = blob.sentiment.polarity
    subjectivity = blob.sentiment.subjectivity

    # Enhanced emotion detection
    if polarity < -0.3:
        emotion = "Stressed/Overwhelmed"
    elif polarity < -0.1:
        emotion = "Uncertain/Anxious"
    elif polarity > 0.3:
        emotion = "Confident/Excited"
    elif polarity > 0.1:
        emotion = "Optimistic"
    else:
        emotion = "Neutral/Focused"

    # Get skill gaps with fallback chain
    skill_gaps = detect_skill_gaps_llm(description, notes)
    if not skill_gaps:  # If LLM fails, use contextual fallback
        skill_gaps = get_contextual_fallback(description, notes)
        print(f"🔄 Using contextual fallback for skill gaps: {skill_gaps}")

    return emotion, skill_gaps, polarity

def process_single_task(task_id: str, desc: str, notes: str) -> Dict:
    """Complete processing pipeline with enhanced output"""
    emotion, skill_gaps, sentiment_score = analyze_text_metadata(desc, notes)

    gaps_with_resources = []
    for skill in skill_gaps:
        resource = generate_tutorial(skill, desc)
        gaps_with_resources.append({
            "skill_gap": skill,
            "mini_tutorial": resource['tutorial'],
            "code_snippet": resource['code_snippet'],
            "resource_link": resource['resource_link'],
            "confidence": "High" if sentiment_score != 0 else "Medium"
        })

    return {
        "task_id": task_id,
        "task_description": desc[:100] + "..." if len(desc) > 100 else desc,
        "employee_notes": notes,
        "emotion_detected": emotion,
        "sentiment_score": round(sentiment_score, 2),
        "detected_skill_gaps": skill_gaps,
        "skill_gaps_with_resources": gaps_with_resources,
        "timestamp": datetime.now().isoformat(),
        "model_version": "Mistral-7B-v0.3-Structured-v5.0"
    }

def load_github_tasks(limit=5):
    """Diverse test cases covering different technologies"""
    sample_tasks = [
        {
            "task_id": "TASK_100",
            "task_description": "Implement a RESTful API endpoint for user authentication using Flask and SQLAlchemy. The API should support user registration, login, and token-based authentication. Ensure proper error handling and input validation.",
            "employee_notes": "I'm struggling with Flask's blueprint architecture and how to integrate SQLAlchemy for user models. Also, I'm not sure how to handle JWT token generation and validation securely."
        },
        {
            "task_id": "TASK_101",
            "task_description": "Optimize a large SQL query that is currently causing performance bottlenecks in the production database. The query involves multiple joins and aggregations on several tables with millions of rows. Identify inefficient parts and suggest improvements.",
            "employee_notes": "I've tried adding some indexes, but it hasn't helped much. I'm not very familiar with query execution plans or advanced SQL optimization techniques like partitioning or materialized views."
        },
        {
            "task_id": "TASK_102",
            "task_description": "Develop a real-time data visualization dashboard using React and D3.js. The dashboard needs to display streaming data from a WebSocket connection, with interactive charts and filtering capabilities.",
            "employee_notes": "I'm comfortable with basic React, but integrating D3.js for complex, dynamic visualizations is new to me. Especially handling data updates from WebSockets and making charts responsive."
        },
        {
            "task_id": "TASK_103",
            "task_description": "Set up a CI/CD pipeline for a new microservice written in Go. The pipeline should include stages for building, testing (unit and integration), and deploying to a Kubernetes cluster. Use GitHub Actions for orchestration.",
            "employee_notes": "I have some experience with basic CI/CD, but deploying to Kubernetes with GitHub Actions is unfamiliar territory. I'm also not sure how to configure Go test coverage reporting in the pipeline."
        },
        {
            "task_id": "TASK_104",
            "task_description": "Write a Python script to automate the generation of daily reports from various Excel files. The script should read data from multiple sheets, perform data cleaning and aggregation, and then generate a summary PDF report using a templating engine.",
            "employee_notes": "I know basic Python scripting, but I've never worked with pandas for data manipulation or a library like ReportLab for PDF generation. I'm also unsure about handling different Excel file formats efficiently."
        }
    ]
    return pd.DataFrame(sample_tasks[:limit])

print("\n🧪 Running Batch Processing Test...")
tasks_df = load_github_tasks(5)
final_results = []

for _, row in tasks_df.iterrows():
    print(f"\n⚙️ Processing {row['task_id']}...")
    result = process_single_task(row['task_id'], row['task_description'], row['employee_notes'])
    final_results.append(result)

    print(f"   Emotion: {result['emotion_detected']}")
    print(f"   Skill Gaps: {result['detected_skill_gaps']}")

# Save results
with open('phase1_llm_fixed_v5.json', 'w') as f:
    json.dump(final_results, f, indent=2)

print("\n✅ Batch processing complete! Results saved to 'phase1_llm_fixed_v5.json'")

print("\n🌐 Launching Gradio Interface...")

def demo_interface(task_desc, notes):
    """Clean interface function"""
    if not task_desc or not notes:
        return {"error": "Please provide both task description and notes"}

    try:
        result = process_single_task("DEMO_TASK", task_desc, notes)
        return result
    except Exception as e:
        return {"error": str(e), "detail": "Check server logs for more information"}

# Create interface with better layout
with gr.Blocks(title="AI Skill Gap Detector v5.0", theme=gr.themes.Soft()) as demo:
    gr.Markdown("""
    # 🎯 AI Skill Gap Detector v5.0
    ### Context-Aware Technical Skill Analysis using Mistral-7B
    """)

    with gr.Row():
        with gr.Column(scale=2):
            task_input = gr.Textbox(
                label="📋 Task Description",
                placeholder="Describe the technical task...",
                lines=5
            )
            notes_input = gr.Textbox(
                label="😰 Employee Notes (Struggles/Confusions)",
                placeholder="What specific parts are confusing or difficult?",
                lines=3
            )
            analyze_btn = gr.Button("🔍 Analyze Skill Gaps", variant="primary")

        with gr.Column(scale=3):
            output = gr.JSON(
                label="📊 Analysis Results",
                height=600
            )

    # Examples for testing
    gr.Examples(
        examples=[
            ["Implement a RESTful API endpoint for user authentication using Flask and SQLAlchemy...", "I'm struggling with Flask's blueprint architecture and how to integrate SQLAlchemy..."],
            ["Optimize a large SQL query that is currently causing performance bottlenecks...", "I've tried adding some indexes, but it hasn't helped much..."]
        ],
        inputs=[task_input, notes_input],
        label="🧪 Try these examples"
    )

    analyze_btn.click(
        fn=demo_interface,
        inputs=[task_input, notes_input],
        outputs=output
    )

# Launch with share=True for Colab
demo.launch(share=True, debug=True)